### PR TITLE
Beta

### PR DESCRIPTION
**Pull request by FrankBuchholz**

### CODE REVIEW

**Comment by FrankBuchholz** [comment]
Try another pull request

**Comment by fluffynuts** [comment]
hm, I just realised that your changes are against what's in `dist`; so I'll need to port into lib/toolwindow. `dist/toolwindow` is generated from `lib/*`, made ready for browsers. Which also explains the odd naming I brought up for captured `this` values -- generated by browserify, when the source had an arrow function :D

**Comment by fluffynuts** [comment]
ok, I've ported across your changes to the lib folder & published. I think you wanted to be able to just link to the code from your own usages -- you can use raw links from https://github.com/fluffynuts/toolwindow/tree/master/dist, eg

https://raw.githubusercontent.com/fluffynuts/toolwindow/master/dist/toolwindow.css
https://raw.githubusercontent.com/fluffynuts/toolwindow/master/dist/toolwindow.js
https://raw.githubusercontent.com/fluffynuts/toolwindow/master/dist/toolwindow.min.js

**Comment by FrankBuchholz** [comment]
Hi Davyd, thats amazing!
Thank you.

I'm still learning how to use GitHub... Next time I'll try to distribute proposals into the original sources. But this would lead to a drawback as long as I do not use the package manager / dist generator you are using: I can test changes only if I put them into the resulting files on dist but I cannot run a live test on changes in the original sources. I guess I then would use two branches: one to modify dist with full test which is not intended to get merged, and another on lib which can be merged.

**Comment by fluffynuts** [comment]
You can test from the original sources - I wrote a helper for that, if you have nodejs installed:

First, (one time) run

`npm install`

Then, run

`npm run autobuild`

As you make changes under the lib folder, it will automatically rebuild the single file in the dist folder. So you could point your test page at that.

I should write this up in the readme, because it's probably not obvious. But this is how I worked on the code, also using (once-off) `npm run launch` which opens the demo index.html in your default browser.

Again, I should document this. I never expected anyone to actually care about this code 🙂 and I'm glad it's been useful for you.

**Pull request merged**
